# Generated by Django 5.2 on 2025-05-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuspost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='statuspost',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='statuspost',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
